package com.android.billingclient.api;

final class zzak {
    static final BillingResult zza;
    static final BillingResult zzb;
    static final BillingResult zzc;
    static final BillingResult zzd;
    static final BillingResult zze;
    static final BillingResult zzf;
    static final BillingResult zzg;
    static final BillingResult zzh;
    static final BillingResult zzi;
    static final BillingResult zzj;
    static final BillingResult zzk;
    static final BillingResult zzl;
    static final BillingResult zzm;
    static final BillingResult zzn;
    static final BillingResult zzo;
    static final BillingResult zzp;
    static final BillingResult zzq;
    static final BillingResult zzr;
    static final BillingResult zzs;
    static final BillingResult zzt;
    static final BillingResult zzu;
    static final BillingResult zzv;

    static {
        Builder billingResult$Builder0 = BillingResult.newBuilder();
        billingResult$Builder0.setResponseCode(3);
        billingResult$Builder0.setDebugMessage("Google Play In-app Billing API version is less than 3");
        zzak.zza = billingResult$Builder0.build();
        Builder billingResult$Builder1 = BillingResult.newBuilder();
        billingResult$Builder1.setResponseCode(3);
        billingResult$Builder1.setDebugMessage("Google Play In-app Billing API version is less than 9");
        zzak.zzb = billingResult$Builder1.build();
        Builder billingResult$Builder2 = BillingResult.newBuilder();
        billingResult$Builder2.setResponseCode(3);
        billingResult$Builder2.setDebugMessage("Billing service unavailable on device.");
        zzak.zzc = billingResult$Builder2.build();
        Builder billingResult$Builder3 = BillingResult.newBuilder();
        billingResult$Builder3.setResponseCode(5);
        billingResult$Builder3.setDebugMessage("Client is already in the process of connecting to billing service.");
        zzak.zzd = billingResult$Builder3.build();
        Builder billingResult$Builder4 = BillingResult.newBuilder();
        billingResult$Builder4.setResponseCode(3);
        billingResult$Builder4.setDebugMessage("Play Store version installed does not support cross selling products.");
        zzak.zze = billingResult$Builder4.build();
        Builder billingResult$Builder5 = BillingResult.newBuilder();
        billingResult$Builder5.setResponseCode(5);
        billingResult$Builder5.setDebugMessage("The list of SKUs can\'t be empty.");
        zzak.zzf = billingResult$Builder5.build();
        Builder billingResult$Builder6 = BillingResult.newBuilder();
        billingResult$Builder6.setResponseCode(5);
        billingResult$Builder6.setDebugMessage("SKU type can\'t be empty.");
        zzak.zzg = billingResult$Builder6.build();
        Builder billingResult$Builder7 = BillingResult.newBuilder();
        billingResult$Builder7.setResponseCode(-2);
        billingResult$Builder7.setDebugMessage("Client does not support extra params.");
        zzak.zzh = billingResult$Builder7.build();
        Builder billingResult$Builder8 = BillingResult.newBuilder();
        billingResult$Builder8.setResponseCode(-2);
        billingResult$Builder8.setDebugMessage("Client does not support the feature.");
        zzak.zzi = billingResult$Builder8.build();
        Builder billingResult$Builder9 = BillingResult.newBuilder();
        billingResult$Builder9.setResponseCode(-2);
        billingResult$Builder9.setDebugMessage("Client does not support get purchase history.");
        zzak.zzj = billingResult$Builder9.build();
        Builder billingResult$Builder10 = BillingResult.newBuilder();
        billingResult$Builder10.setResponseCode(5);
        billingResult$Builder10.setDebugMessage("Invalid purchase token.");
        zzak.zzk = billingResult$Builder10.build();
        Builder billingResult$Builder11 = BillingResult.newBuilder();
        billingResult$Builder11.setResponseCode(6);
        billingResult$Builder11.setDebugMessage("An internal error occurred.");
        zzak.zzl = billingResult$Builder11.build();
        Builder billingResult$Builder12 = BillingResult.newBuilder();
        billingResult$Builder12.setResponseCode(4);
        billingResult$Builder12.setDebugMessage("Item is unavailable for purchase.");
        zzak.zzm = billingResult$Builder12.build();
        Builder billingResult$Builder13 = BillingResult.newBuilder();
        billingResult$Builder13.setResponseCode(5);
        billingResult$Builder13.setDebugMessage("SKU can\'t be null.");
        zzak.zzn = billingResult$Builder13.build();
        Builder billingResult$Builder14 = BillingResult.newBuilder();
        billingResult$Builder14.setResponseCode(5);
        billingResult$Builder14.setDebugMessage("SKU type can\'t be null.");
        zzak.zzo = billingResult$Builder14.build();
        Builder billingResult$Builder15 = BillingResult.newBuilder();
        billingResult$Builder15.setResponseCode(0);
        zzak.zzp = billingResult$Builder15.build();
        Builder billingResult$Builder16 = BillingResult.newBuilder();
        billingResult$Builder16.setResponseCode(-1);
        billingResult$Builder16.setDebugMessage("Service connection is disconnected.");
        zzak.zzq = billingResult$Builder16.build();
        Builder billingResult$Builder17 = BillingResult.newBuilder();
        billingResult$Builder17.setResponseCode(-3);
        billingResult$Builder17.setDebugMessage("Timeout communicating with service.");
        zzak.zzr = billingResult$Builder17.build();
        Builder billingResult$Builder18 = BillingResult.newBuilder();
        billingResult$Builder18.setResponseCode(-2);
        billingResult$Builder18.setDebugMessage("Client doesn\'t support subscriptions.");
        zzak.zzs = billingResult$Builder18.build();
        Builder billingResult$Builder19 = BillingResult.newBuilder();
        billingResult$Builder19.setResponseCode(-2);
        billingResult$Builder19.setDebugMessage("Client doesn\'t support subscriptions update.");
        zzak.zzt = billingResult$Builder19.build();
        Builder billingResult$Builder20 = BillingResult.newBuilder();
        billingResult$Builder20.setResponseCode(-2);
        billingResult$Builder20.setDebugMessage("Client doesn\'t support multi-item purchases.");
        zzak.zzu = billingResult$Builder20.build();
        Builder billingResult$Builder21 = BillingResult.newBuilder();
        billingResult$Builder21.setResponseCode(5);
        billingResult$Builder21.setDebugMessage("Unknown feature");
        zzak.zzv = billingResult$Builder21.build();
    }
}

