package org.lwjgl.openal;

import java.util.Set;
import org.lwjgl.PointerBuffer;
import org.lwjgl.system.APIUtil;
import org.lwjgl.system.FunctionProvider;
import org.lwjgl.system.ThreadLocalUtil;

public final class ALCapabilities {
   public final long alGetError;
   public final long alEnable;
   public final long alDisable;
   public final long alIsEnabled;
   public final long alGetBoolean;
   public final long alGetInteger;
   public final long alGetFloat;
   public final long alGetDouble;
   public final long alGetBooleanv;
   public final long alGetIntegerv;
   public final long alGetFloatv;
   public final long alGetDoublev;
   public final long alGetString;
   public final long alDistanceModel;
   public final long alDopplerFactor;
   public final long alDopplerVelocity;
   public final long alListenerf;
   public final long alListeneri;
   public final long alListener3f;
   public final long alListenerfv;
   public final long alGetListenerf;
   public final long alGetListeneri;
   public final long alGetListener3f;
   public final long alGetListenerfv;
   public final long alGenSources;
   public final long alDeleteSources;
   public final long alIsSource;
   public final long alSourcef;
   public final long alSource3f;
   public final long alSourcefv;
   public final long alSourcei;
   public final long alGetSourcef;
   public final long alGetSource3f;
   public final long alGetSourcefv;
   public final long alGetSourcei;
   public final long alGetSourceiv;
   public final long alSourceQueueBuffers;
   public final long alSourceUnqueueBuffers;
   public final long alSourcePlay;
   public final long alSourcePause;
   public final long alSourceStop;
   public final long alSourceRewind;
   public final long alSourcePlayv;
   public final long alSourcePausev;
   public final long alSourceStopv;
   public final long alSourceRewindv;
   public final long alGenBuffers;
   public final long alDeleteBuffers;
   public final long alIsBuffer;
   public final long alGetBufferf;
   public final long alGetBufferi;
   public final long alBufferData;
   public final long alGetEnumValue;
   public final long alGetProcAddress;
   public final long alIsExtensionPresent;
   public final long alListener3i;
   public final long alGetListeneriv;
   public final long alSource3i;
   public final long alListeneriv;
   public final long alSourceiv;
   public final long alBufferf;
   public final long alBuffer3f;
   public final long alBufferfv;
   public final long alBufferi;
   public final long alBuffer3i;
   public final long alBufferiv;
   public final long alGetBufferiv;
   public final long alGetBufferfv;
   public final long alSpeedOfSound;
   public final long alGenEffects;
   public final long alDeleteEffects;
   public final long alIsEffect;
   public final long alEffecti;
   public final long alEffectiv;
   public final long alEffectf;
   public final long alEffectfv;
   public final long alGetEffecti;
   public final long alGetEffectiv;
   public final long alGetEffectf;
   public final long alGetEffectfv;
   public final long alGenFilters;
   public final long alDeleteFilters;
   public final long alIsFilter;
   public final long alFilteri;
   public final long alFilteriv;
   public final long alFilterf;
   public final long alFilterfv;
   public final long alGetFilteri;
   public final long alGetFilteriv;
   public final long alGetFilterf;
   public final long alGetFilterfv;
   public final long alGenAuxiliaryEffectSlots;
   public final long alDeleteAuxiliaryEffectSlots;
   public final long alIsAuxiliaryEffectSlot;
   public final long alAuxiliaryEffectSloti;
   public final long alAuxiliaryEffectSlotiv;
   public final long alAuxiliaryEffectSlotf;
   public final long alAuxiliaryEffectSlotfv;
   public final long alGetAuxiliaryEffectSloti;
   public final long alGetAuxiliaryEffectSlotiv;
   public final long alGetAuxiliaryEffectSlotf;
   public final long alGetAuxiliaryEffectSlotfv;
   public final long alBufferDataStatic;
   public final long alDeferUpdatesSOFT;
   public final long alProcessUpdatesSOFT;
   public final long alSourcedSOFT;
   public final long alSource3dSOFT;
   public final long alSourcedvSOFT;
   public final long alGetSourcedSOFT;
   public final long alGetSource3dSOFT;
   public final long alGetSourcedvSOFT;
   public final long alSourcei64SOFT;
   public final long alSource3i64SOFT;
   public final long alSourcei64vSOFT;
   public final long alGetSourcei64SOFT;
   public final long alGetSource3i64SOFT;
   public final long alGetSourcei64vSOFT;
   public final long alGetStringiSOFT;
   public final boolean OpenAL10;
   public final boolean OpenAL11;
   public final boolean AL_EXT_ALAW;
   public final boolean AL_EXT_BFORMAT;
   public final boolean AL_EXT_DOUBLE;
   public final boolean ALC_EXT_EFX;
   public final boolean AL_EXT_EXPONENT_DISTANCE;
   public final boolean AL_EXT_FLOAT32;
   public final boolean AL_EXT_IMA4;
   public final boolean AL_EXT_LINEAR_DISTANCE;
   public final boolean AL_EXT_MCFORMATS;
   public final boolean AL_EXT_MULAW;
   public final boolean AL_EXT_MULAW_BFORMAT;
   public final boolean AL_EXT_MULAW_MCFORMATS;
   public final boolean AL_EXT_OFFSET;
   public final boolean AL_EXT_source_distance_model;
   public final boolean AL_EXT_SOURCE_RADIUS;
   public final boolean AL_EXT_static_buffer;
   public final boolean AL_EXT_STEREO_ANGLES;
   public final boolean AL_EXT_vorbis;
   public final boolean AL_LOKI_IMA_ADPCM;
   public final boolean AL_LOKI_quadriphonic;
   public final boolean AL_LOKI_WAVE_format;
   public final boolean AL_SOFT_block_alignment;
   public final boolean AL_SOFT_deferred_updates;
   public final boolean AL_SOFT_direct_channels;
   public final boolean AL_SOFT_gain_clamp_ex;
   public final boolean AL_SOFT_loop_points;
   public final boolean AL_SOFT_MSADPCM;
   public final boolean AL_SOFT_source_latency;
   public final boolean AL_SOFT_source_length;
   public final boolean AL_SOFT_source_resampler;
   public final boolean AL_SOFT_source_spatialize;
   final PointerBuffer addresses;

   ALCapabilities(FunctionProvider provider, Set ext) {
      this.alGetError = provider.getFunctionAddress("alGetError");
      this.alEnable = provider.getFunctionAddress("alEnable");
      this.alDisable = provider.getFunctionAddress("alDisable");
      this.alIsEnabled = provider.getFunctionAddress("alIsEnabled");
      this.alGetBoolean = provider.getFunctionAddress("alGetBoolean");
      this.alGetInteger = provider.getFunctionAddress("alGetInteger");
      this.alGetFloat = provider.getFunctionAddress("alGetFloat");
      this.alGetDouble = provider.getFunctionAddress("alGetDouble");
      this.alGetBooleanv = provider.getFunctionAddress("alGetBooleanv");
      this.alGetIntegerv = provider.getFunctionAddress("alGetIntegerv");
      this.alGetFloatv = provider.getFunctionAddress("alGetFloatv");
      this.alGetDoublev = provider.getFunctionAddress("alGetDoublev");
      this.alGetString = provider.getFunctionAddress("alGetString");
      this.alDistanceModel = provider.getFunctionAddress("alDistanceModel");
      this.alDopplerFactor = provider.getFunctionAddress("alDopplerFactor");
      this.alDopplerVelocity = provider.getFunctionAddress("alDopplerVelocity");
      this.alListenerf = provider.getFunctionAddress("alListenerf");
      this.alListeneri = provider.getFunctionAddress("alListeneri");
      this.alListener3f = provider.getFunctionAddress("alListener3f");
      this.alListenerfv = provider.getFunctionAddress("alListenerfv");
      this.alGetListenerf = provider.getFunctionAddress("alGetListenerf");
      this.alGetListeneri = provider.getFunctionAddress("alGetListeneri");
      this.alGetListener3f = provider.getFunctionAddress("alGetListener3f");
      this.alGetListenerfv = provider.getFunctionAddress("alGetListenerfv");
      this.alGenSources = provider.getFunctionAddress("alGenSources");
      this.alDeleteSources = provider.getFunctionAddress("alDeleteSources");
      this.alIsSource = provider.getFunctionAddress("alIsSource");
      this.alSourcef = provider.getFunctionAddress("alSourcef");
      this.alSource3f = provider.getFunctionAddress("alSource3f");
      this.alSourcefv = provider.getFunctionAddress("alSourcefv");
      this.alSourcei = provider.getFunctionAddress("alSourcei");
      this.alGetSourcef = provider.getFunctionAddress("alGetSourcef");
      this.alGetSource3f = provider.getFunctionAddress("alGetSource3f");
      this.alGetSourcefv = provider.getFunctionAddress("alGetSourcefv");
      this.alGetSourcei = provider.getFunctionAddress("alGetSourcei");
      this.alGetSourceiv = provider.getFunctionAddress("alGetSourceiv");
      this.alSourceQueueBuffers = provider.getFunctionAddress("alSourceQueueBuffers");
      this.alSourceUnqueueBuffers = provider.getFunctionAddress("alSourceUnqueueBuffers");
      this.alSourcePlay = provider.getFunctionAddress("alSourcePlay");
      this.alSourcePause = provider.getFunctionAddress("alSourcePause");
      this.alSourceStop = provider.getFunctionAddress("alSourceStop");
      this.alSourceRewind = provider.getFunctionAddress("alSourceRewind");
      this.alSourcePlayv = provider.getFunctionAddress("alSourcePlayv");
      this.alSourcePausev = provider.getFunctionAddress("alSourcePausev");
      this.alSourceStopv = provider.getFunctionAddress("alSourceStopv");
      this.alSourceRewindv = provider.getFunctionAddress("alSourceRewindv");
      this.alGenBuffers = provider.getFunctionAddress("alGenBuffers");
      this.alDeleteBuffers = provider.getFunctionAddress("alDeleteBuffers");
      this.alIsBuffer = provider.getFunctionAddress("alIsBuffer");
      this.alGetBufferf = provider.getFunctionAddress("alGetBufferf");
      this.alGetBufferi = provider.getFunctionAddress("alGetBufferi");
      this.alBufferData = provider.getFunctionAddress("alBufferData");
      this.alGetEnumValue = provider.getFunctionAddress("alGetEnumValue");
      this.alGetProcAddress = provider.getFunctionAddress("alGetProcAddress");
      this.alIsExtensionPresent = provider.getFunctionAddress("alIsExtensionPresent");
      this.alListener3i = provider.getFunctionAddress("alListener3i");
      this.alGetListeneriv = provider.getFunctionAddress("alGetListeneriv");
      this.alSource3i = provider.getFunctionAddress("alSource3i");
      this.alListeneriv = provider.getFunctionAddress("alListeneriv");
      this.alSourceiv = provider.getFunctionAddress("alSourceiv");
      this.alBufferf = provider.getFunctionAddress("alBufferf");
      this.alBuffer3f = provider.getFunctionAddress("alBuffer3f");
      this.alBufferfv = provider.getFunctionAddress("alBufferfv");
      this.alBufferi = provider.getFunctionAddress("alBufferi");
      this.alBuffer3i = provider.getFunctionAddress("alBuffer3i");
      this.alBufferiv = provider.getFunctionAddress("alBufferiv");
      this.alGetBufferiv = provider.getFunctionAddress("alGetBufferiv");
      this.alGetBufferfv = provider.getFunctionAddress("alGetBufferfv");
      this.alSpeedOfSound = provider.getFunctionAddress("alSpeedOfSound");
      this.alGenEffects = provider.getFunctionAddress("alGenEffects");
      this.alDeleteEffects = provider.getFunctionAddress("alDeleteEffects");
      this.alIsEffect = provider.getFunctionAddress("alIsEffect");
      this.alEffecti = provider.getFunctionAddress("alEffecti");
      this.alEffectiv = provider.getFunctionAddress("alEffectiv");
      this.alEffectf = provider.getFunctionAddress("alEffectf");
      this.alEffectfv = provider.getFunctionAddress("alEffectfv");
      this.alGetEffecti = provider.getFunctionAddress("alGetEffecti");
      this.alGetEffectiv = provider.getFunctionAddress("alGetEffectiv");
      this.alGetEffectf = provider.getFunctionAddress("alGetEffectf");
      this.alGetEffectfv = provider.getFunctionAddress("alGetEffectfv");
      this.alGenFilters = provider.getFunctionAddress("alGenFilters");
      this.alDeleteFilters = provider.getFunctionAddress("alDeleteFilters");
      this.alIsFilter = provider.getFunctionAddress("alIsFilter");
      this.alFilteri = provider.getFunctionAddress("alFilteri");
      this.alFilteriv = provider.getFunctionAddress("alFilteriv");
      this.alFilterf = provider.getFunctionAddress("alFilterf");
      this.alFilterfv = provider.getFunctionAddress("alFilterfv");
      this.alGetFilteri = provider.getFunctionAddress("alGetFilteri");
      this.alGetFilteriv = provider.getFunctionAddress("alGetFilteriv");
      this.alGetFilterf = provider.getFunctionAddress("alGetFilterf");
      this.alGetFilterfv = provider.getFunctionAddress("alGetFilterfv");
      this.alGenAuxiliaryEffectSlots = provider.getFunctionAddress("alGenAuxiliaryEffectSlots");
      this.alDeleteAuxiliaryEffectSlots = provider.getFunctionAddress("alDeleteAuxiliaryEffectSlots");
      this.alIsAuxiliaryEffectSlot = provider.getFunctionAddress("alIsAuxiliaryEffectSlot");
      this.alAuxiliaryEffectSloti = provider.getFunctionAddress("alAuxiliaryEffectSloti");
      this.alAuxiliaryEffectSlotiv = provider.getFunctionAddress("alAuxiliaryEffectSlotiv");
      this.alAuxiliaryEffectSlotf = provider.getFunctionAddress("alAuxiliaryEffectSlotf");
      this.alAuxiliaryEffectSlotfv = provider.getFunctionAddress("alAuxiliaryEffectSlotfv");
      this.alGetAuxiliaryEffectSloti = provider.getFunctionAddress("alGetAuxiliaryEffectSloti");
      this.alGetAuxiliaryEffectSlotiv = provider.getFunctionAddress("alGetAuxiliaryEffectSlotiv");
      this.alGetAuxiliaryEffectSlotf = provider.getFunctionAddress("alGetAuxiliaryEffectSlotf");
      this.alGetAuxiliaryEffectSlotfv = provider.getFunctionAddress("alGetAuxiliaryEffectSlotfv");
      this.alBufferDataStatic = provider.getFunctionAddress("alBufferDataStatic");
      this.alDeferUpdatesSOFT = provider.getFunctionAddress("alDeferUpdatesSOFT");
      this.alProcessUpdatesSOFT = provider.getFunctionAddress("alProcessUpdatesSOFT");
      this.alSourcedSOFT = provider.getFunctionAddress("alSourcedSOFT");
      this.alSource3dSOFT = provider.getFunctionAddress("alSource3dSOFT");
      this.alSourcedvSOFT = provider.getFunctionAddress("alSourcedvSOFT");
      this.alGetSourcedSOFT = provider.getFunctionAddress("alGetSourcedSOFT");
      this.alGetSource3dSOFT = provider.getFunctionAddress("alGetSource3dSOFT");
      this.alGetSourcedvSOFT = provider.getFunctionAddress("alGetSourcedvSOFT");
      this.alSourcei64SOFT = provider.getFunctionAddress("alSourcei64SOFT");
      this.alSource3i64SOFT = provider.getFunctionAddress("alSource3i64SOFT");
      this.alSourcei64vSOFT = provider.getFunctionAddress("alSourcei64vSOFT");
      this.alGetSourcei64SOFT = provider.getFunctionAddress("alGetSourcei64SOFT");
      this.alGetSource3i64SOFT = provider.getFunctionAddress("alGetSource3i64SOFT");
      this.alGetSourcei64vSOFT = provider.getFunctionAddress("alGetSourcei64vSOFT");
      this.alGetStringiSOFT = provider.getFunctionAddress("alGetStringiSOFT");
      this.OpenAL10 = ext.contains("OpenAL10") && checkExtension("OpenAL10", AL10.isAvailable(this));
      this.OpenAL11 = ext.contains("OpenAL11") && checkExtension("OpenAL11", AL11.isAvailable(this));
      this.AL_EXT_ALAW = ext.contains("AL_EXT_ALAW");
      this.AL_EXT_BFORMAT = ext.contains("AL_EXT_BFORMAT");
      this.AL_EXT_DOUBLE = ext.contains("AL_EXT_DOUBLE");
      this.ALC_EXT_EFX = ext.contains("ALC_EXT_EFX") && checkExtension("ALC_EXT_EFX", EXTEfx.isAvailable(this));
      this.AL_EXT_EXPONENT_DISTANCE = ext.contains("AL_EXT_EXPONENT_DISTANCE");
      this.AL_EXT_FLOAT32 = ext.contains("AL_EXT_FLOAT32");
      this.AL_EXT_IMA4 = ext.contains("AL_EXT_IMA4");
      this.AL_EXT_LINEAR_DISTANCE = ext.contains("AL_EXT_LINEAR_DISTANCE");
      this.AL_EXT_MCFORMATS = ext.contains("AL_EXT_MCFORMATS");
      this.AL_EXT_MULAW = ext.contains("AL_EXT_MULAW");
      this.AL_EXT_MULAW_BFORMAT = ext.contains("AL_EXT_MULAW_BFORMAT");
      this.AL_EXT_MULAW_MCFORMATS = ext.contains("AL_EXT_MULAW_MCFORMATS");
      this.AL_EXT_OFFSET = ext.contains("AL_EXT_OFFSET");
      this.AL_EXT_source_distance_model = ext.contains("AL_EXT_source_distance_model");
      this.AL_EXT_SOURCE_RADIUS = ext.contains("AL_EXT_SOURCE_RADIUS");
      this.AL_EXT_static_buffer = ext.contains("AL_EXT_static_buffer") && checkExtension("AL_EXT_static_buffer", EXTStaticBuffer.isAvailable(this));
      this.AL_EXT_STEREO_ANGLES = ext.contains("AL_EXT_STEREO_ANGLES");
      this.AL_EXT_vorbis = ext.contains("AL_EXT_vorbis");
      this.AL_LOKI_IMA_ADPCM = ext.contains("AL_LOKI_IMA_ADPCM");
      this.AL_LOKI_quadriphonic = ext.contains("AL_LOKI_quadriphonic");
      this.AL_LOKI_WAVE_format = ext.contains("AL_LOKI_WAVE_format");
      this.AL_SOFT_block_alignment = ext.contains("AL_SOFT_block_alignment");
      this.AL_SOFT_deferred_updates = ext.contains("AL_SOFT_deferred_updates")
         && checkExtension("AL_SOFT_deferred_updates", SOFTDeferredUpdates.isAvailable(this));
      this.AL_SOFT_direct_channels = ext.contains("AL_SOFT_direct_channels");
      this.AL_SOFT_gain_clamp_ex = ext.contains("AL_SOFT_gain_clamp_ex");
      this.AL_SOFT_loop_points = ext.contains("AL_SOFT_loop_points");
      this.AL_SOFT_MSADPCM = ext.contains("AL_SOFT_MSADPCM");
      this.AL_SOFT_source_latency = ext.contains("AL_SOFT_source_latency") && checkExtension("AL_SOFT_source_latency", SOFTSourceLatency.isAvailable(this));
      this.AL_SOFT_source_length = ext.contains("AL_SOFT_source_length");
      this.AL_SOFT_source_resampler = ext.contains("AL_SOFT_source_resampler")
         && checkExtension("AL_SOFT_source_resampler", SOFTSourceResampler.isAvailable(this));
      this.AL_SOFT_source_spatialize = ext.contains("AL_SOFT_source_spatialize");
      this.addresses = ThreadLocalUtil.getAddressesFromCapabilities(this);
   }

   private static boolean checkExtension(String extension, boolean supported) {
      if (supported) {
         return true;
      } else {
         APIUtil.apiLog("[AL] " + extension + " was reported as available but an entry point is missing.");
         return false;
      }
   }
}
