package org.lwjgl.opengl;

import java.util.Set;
import org.lwjgl.system.APIUtil;
import org.lwjgl.system.FunctionProvider;

public final class GLXCapabilities {
   public final long glXQueryExtensionsString;
   public final long glXGetClientString;
   public final long glXQueryServerString;
   public final long glXGetCurrentDisplay;
   public final long glXGetFBConfigs;
   public final long glXChooseFBConfig;
   public final long glXGetFBConfigAttrib;
   public final long glXGetVisualFromFBConfig;
   public final long glXCreateWindow;
   public final long glXCreatePixmap;
   public final long glXDestroyPixmap;
   public final long glXCreatePbuffer;
   public final long glXDestroyPbuffer;
   public final long glXQueryDrawable;
   public final long glXCreateNewContext;
   public final long glXMakeContextCurrent;
   public final long glXGetCurrentReadDrawable;
   public final long glXQueryContext;
   public final long glXSelectEvent;
   public final long glXGetSelectedEvent;
   public final long glXGetProcAddress;
   public final long glXBlitContextFramebufferAMD;
   public final long glXCreateAssociatedContextAMD;
   public final long glXCreateAssociatedContextAttribsAMD;
   public final long glXDeleteAssociatedContextAMD;
   public final long glXGetContextGPUIDAMD;
   public final long glXGetCurrentAssociatedContextAMD;
   public final long glXGetGPUIDsAMD;
   public final long glXGetGPUInfoAMD;
   public final long glXMakeAssociatedContextCurrentAMD;
   public final long glXCreateContextAttribsARB;
   public final long glXGetProcAddressARB;
   public final long glXGetCurrentDisplayEXT;
   public final long glXQueryContextInfoEXT;
   public final long glXGetContextIDEXT;
   public final long glXImportContextEXT;
   public final long glXFreeContextEXT;
   public final long glXSwapIntervalEXT;
   public final long glXBindTexImageEXT;
   public final long glXReleaseTexImageEXT;
   public final long glXCopyBufferSubDataNV;
   public final long glXNamedCopyBufferSubDataNV;
   public final long glXCopyImageSubDataNV;
   public final long glXDelayBeforeSwapNV;
   public final long glXJoinSwapGroupNV;
   public final long glXBindSwapBarrierNV;
   public final long glXQuerySwapGroupNV;
   public final long glXQueryMaxSwapGroupsNV;
   public final long glXQueryFrameCountNV;
   public final long glXResetFrameCountNV;
   public final long glXMakeCurrentReadSGI;
   public final long glXGetCurrentReadDrawableSGI;
   public final long glXSwapIntervalSGI;
   public final long glXGetVideoSyncSGI;
   public final long glXWaitVideoSyncSGI;
   public final long glXGetFBConfigAttribSGIX;
   public final long glXChooseFBConfigSGIX;
   public final long glXCreateGLXPixmapWithConfigSGIX;
   public final long glXCreateContextWithConfigSGIX;
   public final long glXGetVisualFromFBConfigSGIX;
   public final long glXGetFBConfigFromVisualSGIX;
   public final long glXCreateGLXPbufferSGIX;
   public final long glXDestroyGLXPbufferSGIX;
   public final long glXQueryGLXPbufferSGIX;
   public final long glXSelectEventSGIX;
   public final long glXGetSelectedEventSGIX;
   public final long glXBindSwapBarrierSGIX;
   public final long glXQueryMaxSwapBarriersSGIX;
   public final long glXJoinSwapGroupSGIX;
   public final boolean GLX11;
   public final boolean GLX12;
   public final boolean GLX13;
   public final boolean GLX14;
   public final boolean GLX_AMD_gpu_association;
   public final boolean GLX_ARB_context_flush_control;
   public final boolean GLX_ARB_create_context;
   public final boolean GLX_ARB_create_context_no_error;
   public final boolean GLX_ARB_create_context_profile;
   public final boolean GLX_ARB_create_context_robustness;
   public final boolean GLX_ARB_fbconfig_float;
   public final boolean GLX_ARB_framebuffer_sRGB;
   public final boolean GLX_ARB_get_proc_address;
   public final boolean GLX_ARB_multisample;
   public final boolean GLX_ARB_robustness_application_isolation;
   public final boolean GLX_ARB_robustness_share_group_isolation;
   public final boolean GLX_ARB_vertex_buffer_object;
   public final boolean GLX_EXT_buffer_age;
   public final boolean GLX_EXT_context_priority;
   public final boolean GLX_EXT_create_context_es2_profile;
   public final boolean GLX_EXT_create_context_es_profile;
   public final boolean GLX_EXT_fbconfig_packed_float;
   public final boolean GLX_EXT_framebuffer_sRGB;
   public final boolean GLX_EXT_import_context;
   public final boolean GLX_EXT_no_config_context;
   public final boolean GLX_EXT_stereo_tree;
   public final boolean GLX_EXT_swap_control;
   public final boolean GLX_EXT_swap_control_tear;
   public final boolean GLX_EXT_texture_from_pixmap;
   public final boolean GLX_EXT_visual_info;
   public final boolean GLX_EXT_visual_rating;
   public final boolean GLX_INTEL_swap_event;
   public final boolean GLX_NV_copy_buffer;
   public final boolean GLX_NV_copy_image;
   public final boolean GLX_NV_delay_before_swap;
   public final boolean GLX_NV_float_buffer;
   public final boolean GLX_NV_multisample_coverage;
   public final boolean GLX_NV_robustness_video_memory_purge;
   public final boolean GLX_NV_swap_group;
   public final boolean GLX_SGI_make_current_read;
   public final boolean GLX_SGI_swap_control;
   public final boolean GLX_SGI_video_sync;
   public final boolean GLX_SGIX_fbconfig;
   public final boolean GLX_SGIX_pbuffer;
   public final boolean GLX_SGIX_swap_barrier;
   public final boolean GLX_SGIX_swap_group;

   GLXCapabilities(FunctionProvider provider, Set ext) {
      this.glXQueryExtensionsString = provider.getFunctionAddress("glXQueryExtensionsString");
      this.glXGetClientString = provider.getFunctionAddress("glXGetClientString");
      this.glXQueryServerString = provider.getFunctionAddress("glXQueryServerString");
      this.glXGetCurrentDisplay = provider.getFunctionAddress("glXGetCurrentDisplay");
      this.glXGetFBConfigs = provider.getFunctionAddress("glXGetFBConfigs");
      this.glXChooseFBConfig = provider.getFunctionAddress("glXChooseFBConfig");
      this.glXGetFBConfigAttrib = provider.getFunctionAddress("glXGetFBConfigAttrib");
      this.glXGetVisualFromFBConfig = provider.getFunctionAddress("glXGetVisualFromFBConfig");
      this.glXCreateWindow = provider.getFunctionAddress("glXCreateWindow");
      this.glXCreatePixmap = provider.getFunctionAddress("glXCreatePixmap");
      this.glXDestroyPixmap = provider.getFunctionAddress("glXDestroyPixmap");
      this.glXCreatePbuffer = provider.getFunctionAddress("glXCreatePbuffer");
      this.glXDestroyPbuffer = provider.getFunctionAddress("glXDestroyPbuffer");
      this.glXQueryDrawable = provider.getFunctionAddress("glXQueryDrawable");
      this.glXCreateNewContext = provider.getFunctionAddress("glXCreateNewContext");
      this.glXMakeContextCurrent = provider.getFunctionAddress("glXMakeContextCurrent");
      this.glXGetCurrentReadDrawable = provider.getFunctionAddress("glXGetCurrentReadDrawable");
      this.glXQueryContext = provider.getFunctionAddress("glXQueryContext");
      this.glXSelectEvent = provider.getFunctionAddress("glXSelectEvent");
      this.glXGetSelectedEvent = provider.getFunctionAddress("glXGetSelectedEvent");
      this.glXGetProcAddress = provider.getFunctionAddress("glXGetProcAddress");
      this.glXBlitContextFramebufferAMD = provider.getFunctionAddress("glXBlitContextFramebufferAMD");
      this.glXCreateAssociatedContextAMD = provider.getFunctionAddress("glXCreateAssociatedContextAMD");
      this.glXCreateAssociatedContextAttribsAMD = provider.getFunctionAddress("glXCreateAssociatedContextAttribsAMD");
      this.glXDeleteAssociatedContextAMD = provider.getFunctionAddress("glXDeleteAssociatedContextAMD");
      this.glXGetContextGPUIDAMD = provider.getFunctionAddress("glXGetContextGPUIDAMD");
      this.glXGetCurrentAssociatedContextAMD = provider.getFunctionAddress("glXGetCurrentAssociatedContextAMD");
      this.glXGetGPUIDsAMD = provider.getFunctionAddress("glXGetGPUIDsAMD");
      this.glXGetGPUInfoAMD = provider.getFunctionAddress("glXGetGPUInfoAMD");
      this.glXMakeAssociatedContextCurrentAMD = provider.getFunctionAddress("glXMakeAssociatedContextCurrentAMD");
      this.glXCreateContextAttribsARB = provider.getFunctionAddress("glXCreateContextAttribsARB");
      this.glXGetProcAddressARB = provider.getFunctionAddress("glXGetProcAddressARB");
      this.glXGetCurrentDisplayEXT = provider.getFunctionAddress("glXGetCurrentDisplayEXT");
      this.glXQueryContextInfoEXT = provider.getFunctionAddress("glXQueryContextInfoEXT");
      this.glXGetContextIDEXT = provider.getFunctionAddress("glXGetContextIDEXT");
      this.glXImportContextEXT = provider.getFunctionAddress("glXImportContextEXT");
      this.glXFreeContextEXT = provider.getFunctionAddress("glXFreeContextEXT");
      this.glXSwapIntervalEXT = provider.getFunctionAddress("glXSwapIntervalEXT");
      this.glXBindTexImageEXT = provider.getFunctionAddress("glXBindTexImageEXT");
      this.glXReleaseTexImageEXT = provider.getFunctionAddress("glXReleaseTexImageEXT");
      this.glXCopyBufferSubDataNV = provider.getFunctionAddress("glXCopyBufferSubDataNV");
      this.glXNamedCopyBufferSubDataNV = provider.getFunctionAddress("glXNamedCopyBufferSubDataNV");
      this.glXCopyImageSubDataNV = provider.getFunctionAddress("glXCopyImageSubDataNV");
      this.glXDelayBeforeSwapNV = provider.getFunctionAddress("glXDelayBeforeSwapNV");
      this.glXJoinSwapGroupNV = provider.getFunctionAddress("glXJoinSwapGroupNV");
      this.glXBindSwapBarrierNV = provider.getFunctionAddress("glXBindSwapBarrierNV");
      this.glXQuerySwapGroupNV = provider.getFunctionAddress("glXQuerySwapGroupNV");
      this.glXQueryMaxSwapGroupsNV = provider.getFunctionAddress("glXQueryMaxSwapGroupsNV");
      this.glXQueryFrameCountNV = provider.getFunctionAddress("glXQueryFrameCountNV");
      this.glXResetFrameCountNV = provider.getFunctionAddress("glXResetFrameCountNV");
      this.glXMakeCurrentReadSGI = provider.getFunctionAddress("glXMakeCurrentReadSGI");
      this.glXGetCurrentReadDrawableSGI = provider.getFunctionAddress("glXGetCurrentReadDrawableSGI");
      this.glXSwapIntervalSGI = provider.getFunctionAddress("glXSwapIntervalSGI");
      this.glXGetVideoSyncSGI = provider.getFunctionAddress("glXGetVideoSyncSGI");
      this.glXWaitVideoSyncSGI = provider.getFunctionAddress("glXWaitVideoSyncSGI");
      this.glXGetFBConfigAttribSGIX = provider.getFunctionAddress("glXGetFBConfigAttribSGIX");
      this.glXChooseFBConfigSGIX = provider.getFunctionAddress("glXChooseFBConfigSGIX");
      this.glXCreateGLXPixmapWithConfigSGIX = provider.getFunctionAddress("glXCreateGLXPixmapWithConfigSGIX");
      this.glXCreateContextWithConfigSGIX = provider.getFunctionAddress("glXCreateContextWithConfigSGIX");
      this.glXGetVisualFromFBConfigSGIX = provider.getFunctionAddress("glXGetVisualFromFBConfigSGIX");
      this.glXGetFBConfigFromVisualSGIX = provider.getFunctionAddress("glXGetFBConfigFromVisualSGIX");
      this.glXCreateGLXPbufferSGIX = provider.getFunctionAddress("glXCreateGLXPbufferSGIX");
      this.glXDestroyGLXPbufferSGIX = provider.getFunctionAddress("glXDestroyGLXPbufferSGIX");
      this.glXQueryGLXPbufferSGIX = provider.getFunctionAddress("glXQueryGLXPbufferSGIX");
      this.glXSelectEventSGIX = provider.getFunctionAddress("glXSelectEventSGIX");
      this.glXGetSelectedEventSGIX = provider.getFunctionAddress("glXGetSelectedEventSGIX");
      this.glXBindSwapBarrierSGIX = provider.getFunctionAddress("glXBindSwapBarrierSGIX");
      this.glXQueryMaxSwapBarriersSGIX = provider.getFunctionAddress("glXQueryMaxSwapBarriersSGIX");
      this.glXJoinSwapGroupSGIX = provider.getFunctionAddress("glXJoinSwapGroupSGIX");
      this.GLX11 = ext.contains("GLX11") && checkExtension("GLX11", org.lwjgl.opengl.GLX11.isAvailable(this));
      this.GLX12 = ext.contains("GLX12") && checkExtension("GLX12", org.lwjgl.opengl.GLX12.isAvailable(this));
      this.GLX13 = ext.contains("GLX13") && checkExtension("GLX13", org.lwjgl.opengl.GLX13.isAvailable(this));
      this.GLX14 = ext.contains("GLX14") && checkExtension("GLX14", org.lwjgl.opengl.GLX14.isAvailable(this));
      this.GLX_AMD_gpu_association = ext.contains("GLX_AMD_gpu_association")
         && checkExtension("GLX_AMD_gpu_association", GLXAMDGPUAssociation.isAvailable(this));
      this.GLX_ARB_context_flush_control = ext.contains("GLX_ARB_context_flush_control");
      this.GLX_ARB_create_context = ext.contains("GLX_ARB_create_context") && checkExtension("GLX_ARB_create_context", GLXARBCreateContext.isAvailable(this));
      this.GLX_ARB_create_context_no_error = ext.contains("GLX_ARB_create_context_no_error");
      this.GLX_ARB_create_context_profile = ext.contains("GLX_ARB_create_context_profile");
      this.GLX_ARB_create_context_robustness = ext.contains("GLX_ARB_create_context_robustness");
      this.GLX_ARB_fbconfig_float = ext.contains("GLX_ARB_fbconfig_float");
      this.GLX_ARB_framebuffer_sRGB = ext.contains("GLX_ARB_framebuffer_sRGB");
      this.GLX_ARB_get_proc_address = ext.contains("GLX_ARB_get_proc_address")
         && checkExtension("GLX_ARB_get_proc_address", GLXARBGetProcAddress.isAvailable(this));
      this.GLX_ARB_multisample = ext.contains("GLX_ARB_multisample");
      this.GLX_ARB_robustness_application_isolation = ext.contains("GLX_ARB_robustness_application_isolation");
      this.GLX_ARB_robustness_share_group_isolation = ext.contains("GLX_ARB_robustness_share_group_isolation");
      this.GLX_ARB_vertex_buffer_object = ext.contains("GLX_ARB_vertex_buffer_object");
      this.GLX_EXT_buffer_age = ext.contains("GLX_EXT_buffer_age");
      this.GLX_EXT_context_priority = ext.contains("GLX_EXT_context_priority");
      this.GLX_EXT_create_context_es2_profile = ext.contains("GLX_EXT_create_context_es2_profile");
      this.GLX_EXT_create_context_es_profile = ext.contains("GLX_EXT_create_context_es_profile");
      this.GLX_EXT_fbconfig_packed_float = ext.contains("GLX_EXT_fbconfig_packed_float");
      this.GLX_EXT_framebuffer_sRGB = ext.contains("GLX_EXT_framebuffer_sRGB");
      this.GLX_EXT_import_context = ext.contains("GLX_EXT_import_context") && checkExtension("GLX_EXT_import_context", GLXEXTImportContext.isAvailable(this));
      this.GLX_EXT_no_config_context = ext.contains("GLX_EXT_no_config_context");
      this.GLX_EXT_stereo_tree = ext.contains("GLX_EXT_stereo_tree");
      this.GLX_EXT_swap_control = ext.contains("GLX_EXT_swap_control") && checkExtension("GLX_EXT_swap_control", GLXEXTSwapControl.isAvailable(this));
      this.GLX_EXT_swap_control_tear = ext.contains("GLX_EXT_swap_control_tear");
      this.GLX_EXT_texture_from_pixmap = ext.contains("GLX_EXT_texture_from_pixmap")
         && checkExtension("GLX_EXT_texture_from_pixmap", GLXEXTTextureFromPixmap.isAvailable(this));
      this.GLX_EXT_visual_info = ext.contains("GLX_EXT_visual_info");
      this.GLX_EXT_visual_rating = ext.contains("GLX_EXT_visual_rating");
      this.GLX_INTEL_swap_event = ext.contains("GLX_INTEL_swap_event");
      this.GLX_NV_copy_buffer = ext.contains("GLX_NV_copy_buffer") && checkExtension("GLX_NV_copy_buffer", GLXNVCopyBuffer.isAvailable(this));
      this.GLX_NV_copy_image = ext.contains("GLX_NV_copy_image") && checkExtension("GLX_NV_copy_image", GLXNVCopyImage.isAvailable(this));
      this.GLX_NV_delay_before_swap = ext.contains("GLX_NV_delay_before_swap")
         && checkExtension("GLX_NV_delay_before_swap", GLXNVDelayBeforeSwap.isAvailable(this));
      this.GLX_NV_float_buffer = ext.contains("GLX_NV_float_buffer");
      this.GLX_NV_multisample_coverage = ext.contains("GLX_NV_multisample_coverage");
      this.GLX_NV_robustness_video_memory_purge = ext.contains("GLX_NV_robustness_video_memory_purge");
      this.GLX_NV_swap_group = ext.contains("GLX_NV_swap_group") && checkExtension("GLX_NV_swap_group", GLXNVSwapGroup.isAvailable(this));
      this.GLX_SGI_make_current_read = ext.contains("GLX_SGI_make_current_read")
         && checkExtension("GLX_SGI_make_current_read", GLXSGIMakeCurrentRead.isAvailable(this));
      this.GLX_SGI_swap_control = ext.contains("GLX_SGI_swap_control") && checkExtension("GLX_SGI_swap_control", GLXSGISwapControl.isAvailable(this));
      this.GLX_SGI_video_sync = ext.contains("GLX_SGI_video_sync") && checkExtension("GLX_SGI_video_sync", GLXSGIVideoSync.isAvailable(this));
      this.GLX_SGIX_fbconfig = ext.contains("GLX_SGIX_fbconfig") && checkExtension("GLX_SGIX_fbconfig", GLXSGIXFBConfig.isAvailable(this));
      this.GLX_SGIX_pbuffer = ext.contains("GLX_SGIX_pbuffer") && checkExtension("GLX_SGIX_pbuffer", GLXSGIXPbuffer.isAvailable(this));
      this.GLX_SGIX_swap_barrier = ext.contains("GLX_SGIX_swap_barrier") && checkExtension("GLX_SGIX_swap_barrier", GLXSGIXSwapBarrier.isAvailable(this));
      this.GLX_SGIX_swap_group = ext.contains("GLX_SGIX_swap_group") && checkExtension("GLX_SGIX_swap_group", GLXSGIXSwapGroup.isAvailable(this));
   }

   private static boolean checkExtension(String extension, boolean supported) {
      if (supported) {
         return true;
      } else {
         APIUtil.apiLog("[GLX] " + extension + " was reported as available but an entry point is missing.");
         return false;
      }
   }
}
