package org.lwjgl.opengl;

import java.util.Set;
import org.lwjgl.system.APIUtil;
import org.lwjgl.system.FunctionProvider;

public final class WGLCapabilities {
   public final long wglGetGPUIDsAMD;
   public final long wglGetGPUInfoAMD;
   public final long wglGetContextGPUIDAMD;
   public final long wglCreateAssociatedContextAMD;
   public final long wglCreateAssociatedContextAttribsAMD;
   public final long wglDeleteAssociatedContextAMD;
   public final long wglMakeAssociatedContextCurrentAMD;
   public final long wglGetCurrentAssociatedContextAMD;
   public final long wglBlitContextFramebufferAMD;
   public final long wglCreateBufferRegionARB;
   public final long wglDeleteBufferRegionARB;
   public final long wglSaveBufferRegionARB;
   public final long wglRestoreBufferRegionARB;
   public final long wglCreateContextAttribsARB;
   public final long wglGetExtensionsStringARB;
   public final long wglMakeContextCurrentARB;
   public final long wglGetCurrentReadDCARB;
   public final long wglCreatePbufferARB;
   public final long wglGetPbufferDCARB;
   public final long wglReleasePbufferDCARB;
   public final long wglDestroyPbufferARB;
   public final long wglQueryPbufferARB;
   public final long wglGetPixelFormatAttribivARB;
   public final long wglGetPixelFormatAttribfvARB;
   public final long wglChoosePixelFormatARB;
   public final long wglBindTexImageARB;
   public final long wglReleaseTexImageARB;
   public final long wglSetPbufferAttribARB;
   public final long wglGetExtensionsStringEXT;
   public final long wglSwapIntervalEXT;
   public final long wglGetSwapIntervalEXT;
   public final long wglCopyImageSubDataNV;
   public final long wglDelayBeforeSwapNV;
   public final long wglDXSetResourceShareHandleNV;
   public final long wglDXOpenDeviceNV;
   public final long wglDXCloseDeviceNV;
   public final long wglDXRegisterObjectNV;
   public final long wglDXUnregisterObjectNV;
   public final long wglDXObjectAccessNV;
   public final long wglDXLockObjectsNV;
   public final long wglDXUnlockObjectsNV;
   public final long wglEnumGpusNV;
   public final long wglEnumGpuDevicesNV;
   public final long wglCreateAffinityDCNV;
   public final long wglEnumGpusFromAffinityDCNV;
   public final long wglDeleteDCNV;
   public final long wglJoinSwapGroupNV;
   public final long wglBindSwapBarrierNV;
   public final long wglQuerySwapGroupNV;
   public final long wglQueryMaxSwapGroupsNV;
   public final long wglQueryFrameCountNV;
   public final long wglResetFrameCountNV;
   public final long wglAllocateMemoryNV;
   public final long wglFreeMemoryNV;
   public final boolean WGL_AMD_gpu_association;
   public final boolean WGL_ARB_buffer_region;
   public final boolean WGL_ARB_context_flush_control;
   public final boolean WGL_ARB_create_context;
   public final boolean WGL_ARB_create_context_no_error;
   public final boolean WGL_ARB_create_context_profile;
   public final boolean WGL_ARB_create_context_robustness;
   public final boolean WGL_ARB_extensions_string;
   public final boolean WGL_ARB_framebuffer_sRGB;
   public final boolean WGL_ARB_make_current_read;
   public final boolean WGL_ARB_multisample;
   public final boolean WGL_ARB_pbuffer;
   public final boolean WGL_ARB_pixel_format;
   public final boolean WGL_ARB_pixel_format_float;
   public final boolean WGL_ARB_render_texture;
   public final boolean WGL_ARB_robustness_application_isolation;
   public final boolean WGL_ARB_robustness_share_group_isolation;
   public final boolean WGL_ATI_pixel_format_float;
   public final boolean WGL_ATI_render_texture_rectangle;
   public final boolean WGL_EXT_colorspace;
   public final boolean WGL_EXT_create_context_es2_profile;
   public final boolean WGL_EXT_create_context_es_profile;
   public final boolean WGL_EXT_depth_float;
   public final boolean WGL_EXT_extensions_string;
   public final boolean WGL_EXT_framebuffer_sRGB;
   public final boolean WGL_EXT_pixel_format_packed_float;
   public final boolean WGL_EXT_swap_control;
   public final boolean WGL_EXT_swap_control_tear;
   public final boolean WGL_NV_copy_image;
   public final boolean WGL_NV_delay_before_swap;
   public final boolean WGL_NV_DX_interop;
   public final boolean WGL_NV_DX_interop2;
   public final boolean WGL_NV_float_buffer;
   public final boolean WGL_NV_gpu_affinity;
   public final boolean WGL_NV_multigpu_context;
   public final boolean WGL_NV_multisample_coverage;
   public final boolean WGL_NV_render_depth_texture;
   public final boolean WGL_NV_render_texture_rectangle;
   public final boolean WGL_NV_swap_group;
   public final boolean WGL_NV_vertex_array_range;

   WGLCapabilities(FunctionProvider provider, Set ext) {
      this.wglGetGPUIDsAMD = provider.getFunctionAddress("wglGetGPUIDsAMD");
      this.wglGetGPUInfoAMD = provider.getFunctionAddress("wglGetGPUInfoAMD");
      this.wglGetContextGPUIDAMD = provider.getFunctionAddress("wglGetContextGPUIDAMD");
      this.wglCreateAssociatedContextAMD = provider.getFunctionAddress("wglCreateAssociatedContextAMD");
      this.wglCreateAssociatedContextAttribsAMD = provider.getFunctionAddress("wglCreateAssociatedContextAttribsAMD");
      this.wglDeleteAssociatedContextAMD = provider.getFunctionAddress("wglDeleteAssociatedContextAMD");
      this.wglMakeAssociatedContextCurrentAMD = provider.getFunctionAddress("wglMakeAssociatedContextCurrentAMD");
      this.wglGetCurrentAssociatedContextAMD = provider.getFunctionAddress("wglGetCurrentAssociatedContextAMD");
      this.wglBlitContextFramebufferAMD = provider.getFunctionAddress("wglBlitContextFramebufferAMD");
      this.wglCreateBufferRegionARB = provider.getFunctionAddress("wglCreateBufferRegionARB");
      this.wglDeleteBufferRegionARB = provider.getFunctionAddress("wglDeleteBufferRegionARB");
      this.wglSaveBufferRegionARB = provider.getFunctionAddress("wglSaveBufferRegionARB");
      this.wglRestoreBufferRegionARB = provider.getFunctionAddress("wglRestoreBufferRegionARB");
      this.wglCreateContextAttribsARB = provider.getFunctionAddress("wglCreateContextAttribsARB");
      this.wglGetExtensionsStringARB = provider.getFunctionAddress("wglGetExtensionsStringARB");
      this.wglMakeContextCurrentARB = provider.getFunctionAddress("wglMakeContextCurrentARB");
      this.wglGetCurrentReadDCARB = provider.getFunctionAddress("wglGetCurrentReadDCARB");
      this.wglCreatePbufferARB = provider.getFunctionAddress("wglCreatePbufferARB");
      this.wglGetPbufferDCARB = provider.getFunctionAddress("wglGetPbufferDCARB");
      this.wglReleasePbufferDCARB = provider.getFunctionAddress("wglReleasePbufferDCARB");
      this.wglDestroyPbufferARB = provider.getFunctionAddress("wglDestroyPbufferARB");
      this.wglQueryPbufferARB = provider.getFunctionAddress("wglQueryPbufferARB");
      this.wglGetPixelFormatAttribivARB = provider.getFunctionAddress("wglGetPixelFormatAttribivARB");
      this.wglGetPixelFormatAttribfvARB = provider.getFunctionAddress("wglGetPixelFormatAttribfvARB");
      this.wglChoosePixelFormatARB = provider.getFunctionAddress("wglChoosePixelFormatARB");
      this.wglBindTexImageARB = provider.getFunctionAddress("wglBindTexImageARB");
      this.wglReleaseTexImageARB = provider.getFunctionAddress("wglReleaseTexImageARB");
      this.wglSetPbufferAttribARB = provider.getFunctionAddress("wglSetPbufferAttribARB");
      this.wglGetExtensionsStringEXT = provider.getFunctionAddress("wglGetExtensionsStringEXT");
      this.wglSwapIntervalEXT = provider.getFunctionAddress("wglSwapIntervalEXT");
      this.wglGetSwapIntervalEXT = provider.getFunctionAddress("wglGetSwapIntervalEXT");
      this.wglCopyImageSubDataNV = provider.getFunctionAddress("wglCopyImageSubDataNV");
      this.wglDelayBeforeSwapNV = provider.getFunctionAddress("wglDelayBeforeSwapNV");
      this.wglDXSetResourceShareHandleNV = provider.getFunctionAddress("wglDXSetResourceShareHandleNV");
      this.wglDXOpenDeviceNV = provider.getFunctionAddress("wglDXOpenDeviceNV");
      this.wglDXCloseDeviceNV = provider.getFunctionAddress("wglDXCloseDeviceNV");
      this.wglDXRegisterObjectNV = provider.getFunctionAddress("wglDXRegisterObjectNV");
      this.wglDXUnregisterObjectNV = provider.getFunctionAddress("wglDXUnregisterObjectNV");
      this.wglDXObjectAccessNV = provider.getFunctionAddress("wglDXObjectAccessNV");
      this.wglDXLockObjectsNV = provider.getFunctionAddress("wglDXLockObjectsNV");
      this.wglDXUnlockObjectsNV = provider.getFunctionAddress("wglDXUnlockObjectsNV");
      this.wglEnumGpusNV = provider.getFunctionAddress("wglEnumGpusNV");
      this.wglEnumGpuDevicesNV = provider.getFunctionAddress("wglEnumGpuDevicesNV");
      this.wglCreateAffinityDCNV = provider.getFunctionAddress("wglCreateAffinityDCNV");
      this.wglEnumGpusFromAffinityDCNV = provider.getFunctionAddress("wglEnumGpusFromAffinityDCNV");
      this.wglDeleteDCNV = provider.getFunctionAddress("wglDeleteDCNV");
      this.wglJoinSwapGroupNV = provider.getFunctionAddress("wglJoinSwapGroupNV");
      this.wglBindSwapBarrierNV = provider.getFunctionAddress("wglBindSwapBarrierNV");
      this.wglQuerySwapGroupNV = provider.getFunctionAddress("wglQuerySwapGroupNV");
      this.wglQueryMaxSwapGroupsNV = provider.getFunctionAddress("wglQueryMaxSwapGroupsNV");
      this.wglQueryFrameCountNV = provider.getFunctionAddress("wglQueryFrameCountNV");
      this.wglResetFrameCountNV = provider.getFunctionAddress("wglResetFrameCountNV");
      this.wglAllocateMemoryNV = provider.getFunctionAddress("wglAllocateMemoryNV");
      this.wglFreeMemoryNV = provider.getFunctionAddress("wglFreeMemoryNV");
      this.WGL_AMD_gpu_association = ext.contains("WGL_AMD_gpu_association")
         && checkExtension("WGL_AMD_gpu_association", WGLAMDGPUAssociation.isAvailable(this));
      this.WGL_ARB_buffer_region = ext.contains("WGL_ARB_buffer_region") && checkExtension("WGL_ARB_buffer_region", WGLARBBufferRegion.isAvailable(this));
      this.WGL_ARB_context_flush_control = ext.contains("WGL_ARB_context_flush_control");
      this.WGL_ARB_create_context = ext.contains("WGL_ARB_create_context") && checkExtension("WGL_ARB_create_context", WGLARBCreateContext.isAvailable(this));
      this.WGL_ARB_create_context_no_error = ext.contains("WGL_ARB_create_context_no_error");
      this.WGL_ARB_create_context_profile = ext.contains("WGL_ARB_create_context_profile");
      this.WGL_ARB_create_context_robustness = ext.contains("WGL_ARB_create_context_robustness");
      this.WGL_ARB_extensions_string = ext.contains("WGL_ARB_extensions_string")
         && checkExtension("WGL_ARB_extensions_string", WGLARBExtensionsString.isAvailable(this));
      this.WGL_ARB_framebuffer_sRGB = ext.contains("WGL_ARB_framebuffer_sRGB");
      this.WGL_ARB_make_current_read = ext.contains("WGL_ARB_make_current_read")
         && checkExtension("WGL_ARB_make_current_read", WGLARBMakeCurrentRead.isAvailable(this));
      this.WGL_ARB_multisample = ext.contains("WGL_ARB_multisample");
      this.WGL_ARB_pbuffer = ext.contains("WGL_ARB_pbuffer") && checkExtension("WGL_ARB_pbuffer", WGLARBPbuffer.isAvailable(this));
      this.WGL_ARB_pixel_format = ext.contains("WGL_ARB_pixel_format") && checkExtension("WGL_ARB_pixel_format", WGLARBPixelFormat.isAvailable(this));
      this.WGL_ARB_pixel_format_float = ext.contains("WGL_ARB_pixel_format_float");
      this.WGL_ARB_render_texture = ext.contains("WGL_ARB_render_texture") && checkExtension("WGL_ARB_render_texture", WGLARBRenderTexture.isAvailable(this));
      this.WGL_ARB_robustness_application_isolation = ext.contains("WGL_ARB_robustness_application_isolation");
      this.WGL_ARB_robustness_share_group_isolation = ext.contains("WGL_ARB_robustness_share_group_isolation");
      this.WGL_ATI_pixel_format_float = ext.contains("WGL_ATI_pixel_format_float");
      this.WGL_ATI_render_texture_rectangle = ext.contains("WGL_ATI_render_texture_rectangle");
      this.WGL_EXT_colorspace = ext.contains("WGL_EXT_colorspace");
      this.WGL_EXT_create_context_es2_profile = ext.contains("WGL_EXT_create_context_es2_profile");
      this.WGL_EXT_create_context_es_profile = ext.contains("WGL_EXT_create_context_es_profile");
      this.WGL_EXT_depth_float = ext.contains("WGL_EXT_depth_float");
      this.WGL_EXT_extensions_string = ext.contains("WGL_EXT_extensions_string")
         && checkExtension("WGL_EXT_extensions_string", WGLEXTExtensionsString.isAvailable(this));
      this.WGL_EXT_framebuffer_sRGB = ext.contains("WGL_EXT_framebuffer_sRGB");
      this.WGL_EXT_pixel_format_packed_float = ext.contains("WGL_EXT_pixel_format_packed_float");
      this.WGL_EXT_swap_control = ext.contains("WGL_EXT_swap_control") && checkExtension("WGL_EXT_swap_control", WGLEXTSwapControl.isAvailable(this));
      this.WGL_EXT_swap_control_tear = ext.contains("WGL_EXT_swap_control_tear");
      this.WGL_NV_copy_image = ext.contains("WGL_NV_copy_image") && checkExtension("WGL_NV_copy_image", WGLNVCopyImage.isAvailable(this));
      this.WGL_NV_delay_before_swap = ext.contains("WGL_NV_delay_before_swap")
         && checkExtension("WGL_NV_delay_before_swap", WGLNVDelayBeforeSwap.isAvailable(this));
      this.WGL_NV_DX_interop = ext.contains("WGL_NV_DX_interop") && checkExtension("WGL_NV_DX_interop", WGLNVDXInterop.isAvailable(this));
      this.WGL_NV_DX_interop2 = ext.contains("WGL_NV_DX_interop2");
      this.WGL_NV_float_buffer = ext.contains("WGL_NV_float_buffer");
      this.WGL_NV_gpu_affinity = ext.contains("WGL_NV_gpu_affinity") && checkExtension("WGL_NV_gpu_affinity", WGLNVGPUAffinity.isAvailable(this));
      this.WGL_NV_multigpu_context = ext.contains("WGL_NV_multigpu_context");
      this.WGL_NV_multisample_coverage = ext.contains("WGL_NV_multisample_coverage");
      this.WGL_NV_render_depth_texture = ext.contains("WGL_NV_render_depth_texture");
      this.WGL_NV_render_texture_rectangle = ext.contains("WGL_NV_render_texture_rectangle");
      this.WGL_NV_swap_group = ext.contains("WGL_NV_swap_group") && checkExtension("WGL_NV_swap_group", WGLNVSwapGroup.isAvailable(this));
      this.WGL_NV_vertex_array_range = ext.contains("WGL_NV_vertex_array_range")
         && checkExtension("WGL_NV_vertex_array_range", WGLNVVertexArrayRange.isAvailable(this));
   }

   private static boolean checkExtension(String extension, boolean supported) {
      if (supported) {
         return true;
      } else {
         APIUtil.apiLog("[WGL] " + extension + " was reported as available but an entry point is missing.");
         return false;
      }
   }
}
